name: Broken link check

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@{version}
      with:
        url: 'https://devonfw.com' 
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}" 


